use std::collections::HashMap;

pub fn propagate() -> HashMap<&'static str, &'static str> {
    HashMap::from([
        ("Abkhaz", "abk"),
        ("Abaza", "abq"),
        ("Iraqi Arabic", "acm"),
        ("Adyghe", "ady"),
        ("Gulf Arabic", "afb"),
        ("Afrihili", "afh"),
        ("Afrikaans", "afr"),
        ("Assyrian Neo-aramaic", "aii"),
        ("Ainu", "ain"),
        ("South Levantine Arabic", "ajp"),
        ("Aklanon", "akl"),
        ("Gheg Albanian", "aln"),
        ("Southern Altai", "alt"),
        ("Amharic", "amh"),
        ("Old English", "ang"),
        ("Uab Meto", "aoz"),
        ("North Levantine Arabic", "apc"),
        ("Arabic", "ara"),
        ("Aragonese", "arg"),
        ("Algerian Arabic", "arq"),
        ("Moroccan Arabic", "ary"),
        ("Egyptian Arabic", "arz"),
        ("Assamese", "asm"),
        ("Asturian", "ast"),
        ("Avar", "ava"),
        ("Kotava", "avk"),
        ("Awadhi", "awa"),
        ("Libyan Arabic", "ayl"),
        ("Aymara", "aym"),
        ("Azerbaijani", "aze"),
        ("Bashkir", "bak"),
        ("Baluchi", "bal"),
        ("Bambara", "bam"),
        ("Balinese", "ban"),
        ("Bavarian", "bar"),
        ("Central Bikol", "bcl"),
        ("Belarusian", "bel"),
        ("Bengali", "ben"),
        ("Berber", "ber"),
        ("Mahasu Pahari", "bfz"),
        ("Bhojpuri", "bho"),
        ("Bislama", "bis"),
        ("Banjar", "bjn"),
        ("Tibetan", "bod"),
        ("Berom", "bom"),
        ("Bosnian", "bos"),
        ("Breton", "bre"),
        ("Bodo", "brx"),
        ("Buryat", "bua"),
        ("Bulgarian", "bul"),
        ("Baybayanon", "bvy"),
        ("Brithenig", "bzt"),
        ("Catalan", "cat"),
        ("Cayuga", "cay"),
        ("Chavacano", "cbk"),
        ("Cebuano", "ceb"),
        ("Czech", "ces"),
        ("Chamorro", "cha"),
        ("Chechen", "che"),
        ("Chagatai", "chg"),
        ("Chinook Jargon", "chn"),
        ("Choctaw", "cho"),
        ("Cherokee", "chr"),
        ("Chuvash", "chv"),
        ("Jin Chinese", "cjy"),
        ("Central Kurdish (Soranî)", "ckb"),
        ("Chukchi", "ckt"),
        ("Mandarin Chinese", "cmn"),
        ("Central Mnong", "cmo"),
        ("Cornish", "cor"),
        ("Corsican", "cos"),
        ("Chinese Pidgin English", "cpi"),
        ("Crimean Tatar", "crh"),
        ("Plains Cree", "crk"),
        ("Seychellois Creole", "crs"),
        ("Kashubian", "csb"),
        ("Cycl", "cycl"),
        ("Welsh", "cym"),
        ("Cuyonon", "cyo"),
        ("Danish", "dan"),
        ("Dargwa", "dar"),
        ("German", "deu"),
        ("Southern Zaza (Dimli)", "diq"),
        ("Dhivehi", "div"),
        ("Dungan", "dng"),
        ("Drents", "drt"),
        ("Lower Sorbian", "dsb"),
        ("Central Dusun", "dtp"),
        ("Dutton World Speedwords", "dws"),
        ("Emilian", "egl"),
        ("Greek", "ell"),
        ("Erromintxela", "emx"),
        ("English", "eng"),
        ("Middle English", "enm"),
        ("Esperanto", "epo"),
        ("Estonian", "est"),
        ("Basque", "eus"),
        ("Evenki", "evn"),
        ("Ewe", "ewe"),
        ("Extremaduran", "ext"),
        ("Faroese", "fao"),
        ("Fijian", "fij"),
        ("Finnish", "fin"),
        ("Kven Finnish", "fkv"),
        ("French", "fra"),
        ("Middle French", "frm"),
        ("Old French", "fro"),
        ("North Frisian", "frr"),
        ("Frisian", "fry"),
        ("Pulaar", "fuc"),
        ("Friulian", "fur"),
        ("Nigerian Fulfulde", "fuv"),
        ("Ga", "gaa"),
        ("Gagauz", "gag"),
        ("Gan Chinese", "gan"),
        ("Garhwali", "gbm"),
        ("Guadeloupean Creole French", "gcf"),
        ("Gilbertese", "gil"),
        ("Scottish Gaelic", "gla"),
        ("Irish", "gle"),
        ("Galician", "glg"),
        ("Manx", "glv"),
        ("Konkani (Goan)", "gom"),
        ("Gronings", "gos"),
        ("Gothic", "got"),
        ("Ancient Greek", "grc"),
        ("Guarani", "grn"),
        ("Swiss German", "gsw"),
        ("Wayuu", "guc"),
        ("Gujarati", "guj"),
        ("Hakka Chinese", "hak"),
        ("Haitian Creole", "hat"),
        ("Hausa", "hau"),
        ("Hawaiian", "haw"),
        ("Southern Haida", "hax"),
        ("Ancient Hebrew", "hbo"),
        ("Northern Haida", "hdn"),
        ("Hebrew", "heb"),
        ("Fiji Hindi", "hif"),
        ("Hiligaynon", "hil"),
        ("Hindi", "hin"),
        ("Hmong Njua (Green)", "hnj"),
        ("Ho", "hoc"),
        ("Croatian", "hrv"),
        ("Hunsrik", "hrx"),
        ("Upper Sorbian", "hsb"),
        ("Xiang Chinese", "hsn"),
        ("Hungarian", "hun"),
        ("Armenian", "hye"),
        ("Iban", "iba"),
        ("Igbo", "ibo"),
        ("Ido", "ido"),
        ("Interglossa", "igs"),
        ("Nuosu", "iii"),
        ("Inuktitut", "ike"),
        ("Interlingue", "ile"),
        ("Ilocano", "ilo"),
        ("Interlingua", "ina"),
        ("Indonesian", "ind"),
        ("Ingush", "inh"),
        ("Icelandic", "isl"),
        ("Italian", "ita"),
        ("Ingrian", "izh"),
        ("Jamaican Patois", "jam"),
        ("Javanese", "jav"),
        ("Lojban", "jbo"),
        ("Juhuri (Judeo-tat)", "jdt"),
        ("Jewish Palestinian Aramaic", "jpa"),
        ("Japanese", "jpn"),
        ("Karakalpak", "kaa"),
        ("Kabyle", "kab"),
        ("Greenlandic", "kal"),
        ("Kamba", "kam"),
        ("Kannada", "kan"),
        ("Kashmiri", "kas"),
        ("Georgian", "kat"),
        ("Kazakh", "kaz"),
        ("Kabardian", "kbd"),
        ("Kekchi (Q'eqchi')", "kek"),
        ("Khasi", "kha"),
        ("Khmer", "khm"),
        ("Kinyarwanda", "kin"),
        ("Kyrgyz", "kir"),
        ("Northern Zaza (Kirmanjki)", "kiu"),
        ("Khakas", "kjh"),
        ("Khalaj", "klj"),
        ("Northern Kurdish (Kurmancî)", "kmr"),
        ("Central Kanuri", "knc"),
        ("Komi-permyak", "koi"),
        ("Korean", "kor"),
        ("Komi-zyrian", "kpv"),
        ("Karachay-balkar", "krc"),
        ("Karelian", "krl"),
        ("Kölsch", "ksh"),
        ("Kumyk", "kum"),
        ("Keningau Murut", "kxi"),
        ("Coastal Kadazan", "kzj"),
        ("Southern Subanen", "laa"),
        ("Ladino", "lad"),
        ("Lao", "lao"),
        ("Latin", "lat"),
        ("Lak", "lbe"),
        ("Láadan", "ldn"),
        ("Lezgi", "lez"),
        ("Lingua Franca Nova", "lfn"),
        ("Ligurian", "lij"),
        ("Limburgish", "lim"),
        ("Lingala", "lin"),
        ("Lithuanian", "lit"),
        ("Livonian", "liv"),
        ("Lakota", "lkt"),
        ("Ladin", "lld"),
        ("Lombard", "lmo"),
        ("Louisiana Creole", "lou"),
        ("Latgalian", "ltg"),
        ("Luxembourgish", "ltz"),
        ("Luganda", "lug"),
        ("Lushootseed", "lut"),
        ("Latvian", "lvs"),
        ("Literary Chinese", "lzh"),
        ("Laz", "lzz"),
        ("Madurese", "mad"),
        ("Marshallese", "mah"),
        ("Maithili", "mai"),
        ("Malayalam", "mal"),
        ("Marathi", "mar"),
        ("North Moluccan Malay", "max"),
        ("Moksha", "mdf"),
        ("Kelantan-pattani Malay", "mfa"),
        ("Morisyen", "mfe"),
        ("Mambae", "mgm"),
        ("Meadow Mari", "mhr"),
        ("Mi'kmaq", "mic"),
        ("Hitchiti", "mik"),
        ("Minangkabau", "min"),
        ("Macedonian", "mkd"),
        ("Malagasy", "mlg"),
        ("Maltese", "mlt"),
        ("Manchu", "mnc"),
        ("Meitei", "mni"),
        ("Mono (USA)", "mnr"),
        ("Mon", "mnw"),
        ("Mohawk", "moh"),
        ("Mongolian", "mon"),
        ("Maori", "mri"),
        ("Hill Mari", "mrj"),
        ("Muskogee (Creek)", "mus"),
        ("Tagal Murut", "mvv"),
        ("Mirandese", "mwl"),
        ("Hmong Daw (White)", "mww"),
        ("Burmese", "mya"),
        ("Erzya", "myv"),
        ("Nahuatl", "nah"),
        ("Min Nan Chinese", "nan"),
        ("Neapolitan", "nap"),
        ("Nauruan", "nau"),
        ("Navajo", "nav"),
        ("Central Huasteca Nahuatl", "nch"),
        ("Low German (Low saxon)", "nds"),
        ("Newari", "new"),
        ("Ngeq ", "ngt"),
        ("Guerrero Nahuatl", "ngu"),
        ("Niuean", "niu"),
        ("Dutch", "nld"),
        ("Orizaba Nahuatl", "nlv"),
        ("Nande", "nnb"),
        ("Norwegian Nynorsk", "nno"),
        ("Norwegian Bokmål", "nob"),
        ("Nogai", "nog"),
        ("Old Norse", "non"),
        ("Novial", "nov"),
        ("Nepali", "npi"),
        ("Naga (Tangshang)", "nst"),
        ("Nuer", "nus"),
        ("Chinyanja", "nya"),
        ("Nyungar", "nys"),
        ("Old Aramaic", "oar"),
        ("Occitan", "oci"),
        ("Old Frisian", "ofs"),
        ("Ojibwe", "oji"),
        ("O'odham", "ood"),
        ("Odia (Oriya)", "ori"),
        ("Old East Slavic", "orv"),
        ("Old Spanish", "osp"),
        ("Ossetian", "oss"),
        ("Old Saxon", "osx"),
        ("Ottoman Turkish", "ota"),
        ("Old Turkish", "otk"),
        ("Pangasinan", "pag"),
        ("Middle Persian (Pahlavi)", "pal"),
        ("Kapampangan", "pam"),
        ("Punjabi (Eastern)", "pan"),
        ("Papiamento", "pap"),
        ("Palauan", "pau"),
        ("Picard", "pcd"),
        ("Pennsylvania German", "pdc"),
        ("Persian", "pes"),
        ("Palatine German", "pfl"),
        ("Phoenician", "phn"),
        ("Pali", "pli"),
        ("Piedmontese", "pms"),
        ("Punjabi (Western)", "pnb"),
        ("Polish", "pol"),
        ("Portuguese", "por"),
        ("Pipil", "ppl"),
        ("Old Prussian", "prg"),
        ("Pashto", "pus"),
        ("K'iche'", "quc"),
        ("Quechua", "que"),
        ("Qashqai", "qxq"),
        ("Quenya", "qya"),
        ("Rapa Nui", "rap"),
        ("Rendille", "rel"),
        ("Rohingya", "rhg"),
        ("Tarifit", "rif"),
        ("Romansh", "roh"),
        ("Romani", "rom"),
        ("Romanian", "ron"),
        ("Rusyn", "rue"),
        ("Kirundi", "run"),
        ("Russian", "rus"),
        ("Okinawan", "ryu"),
        ("Sango", "sag"),
        ("Yakut", "sah"),
        ("Sanskrit", "san"),
        ("Santali", "sat"),
        ("Sicilian", "scn"),
        ("Scots", "sco"),
        ("Southern Kurdish", "sdh"),
        ("Samogitian", "sgs"),
        ("Tashelhit", "shi"),
        ("Shuswap", "shs"),
        ("Tachawit", "shy"),
        ("Sinhala", "sin"),
        ("Sindarin", "sjn"),
        ("Saraiki", "skr"),
        ("Slovak", "slk"),
        ("Slovenian", "slv"),
        ("Southern Sami", "sma"),
        ("Northern Sami", "sme"),
        ("Samoan", "smo"),
        ("Shona", "sna"),
        ("Sindhi", "snd"),
        ("Somali", "som"),
        ("Southern Sotho", "sot"),
        ("Spanish", "spa"),
        ("Albanian", "sqi"),
        ("Sardinian", "srd"),
        ("Sranan Tongo", "srn"),
        ("Serbian", "srp"),
        ("Swazi", "ssw"),
        ("Saterland Frisian", "stq"),
        ("Sundanese", "sun"),
        ("Sumerian", "sux"),
        ("Congo Swahili", "swc"),
        ("Swedish", "swe"),
        ("Swabian", "swg"),
        ("Swahili", "swh"),
        ("Syriac", "syc"),
        ("Silesian", "szl"),
        ("Tahitian", "tah"),
        ("Tamil", "tam"),
        ("Tatar", "tat"),
        ("Telugu", "tel"),
        ("Tetun", "tet"),
        ("Tajik", "tgk"),
        ("Tagalog", "tgl"),
        ("Thai", "tha"),
        ("Tahaggart Tamahaq", "thv"),
        ("Tigre", "tig"),
        ("Tigrinya", "tir"),
        ("Tokelauan", "tkl"),
        ("Klingon", "tlh"),
        ("Talysh", "tly"),
        ("Jewish Babylonian Aramaic", "tmr"),
        ("Temuan", "tmw"),
        ("Tonga (Zambezi)", "toi"),
        ("Toki Pona", "tok"),
        ("Tongan", "ton"),
        ("Tok Pisin", "tpi"),
        ("Old Tupi", "tpw"),
        ("Setswana", "tsn"),
        ("Tsonga", "tso"),
        ("Isan", "tts"),
        ("Turkmen", "tuk"),
        ("Turkish", "tur"),
        ("Tuvaluan", "tvl"),
        ("Tuvinian", "tyv"),
        ("Talossan", "tzl"),
        ("Udmurt", "udm"),
        ("Uyghur", "uig"),
        ("Ukrainian", "ukr"),
        ("Umbundu", "umb"),
        ("Urdu", "urd"),
        ("Urhobo", "urh"),
        ("Uzbek", "uzb"),
        ("Venetian", "vec"),
        ("Veps", "vep"),
        ("Vietnamese", "vie"),
        ("Volapük", "vol"),
        ("Võro", "vro"),
        ("Waray", "war"),
        ("Walloon", "wln"),
        ("Wolof", "wol"),
        ("Shanghainese", "wuu"),
        ("Kalmyk", "xal"),
        ("Xhosa", "xho"),
        ("Mingrelian", "xmf"),
        ("Karakhanid", "xqa"),
        ("Yiddish", "yid"),
        ("Yoruba", "yor"),
        ("Yucatec Maya", "yua"),
        ("Cantonese", "yue"),
        ("Zeelandic", "zea"),
        ("Standard Moroccan Tamazight", "zgh"),
        ("Malay (Vernacular)", "zlm"),
        ("Malay", "zsm"),
        ("Zulu", "zul"),
        ("Zaza", "zza"),
    ])
}
